direction: right
classes: {
  https: {
    style: {
      font-color: black
      stroke-width: 3
      stroke: black
    }
  }
  https+signature: {
    style: {
      font-color: green
      stroke-width: 3
      stroke: green
    }
  }
  https+signature+provenance: {
    style: {
      font-color: blue
      stroke-width: 3
      stroke: blue
    }
  }
}
vars: {
  d2-config: {
    layout-engine: elk
    # Terminal theme code
    # theme-id: 300
    # sketch: true
  }
  d2-legend: {
    a -> b: HTTPS + Signature Verification + Provenance Verification {
      class: https+signature+provenance
    }
    a -> b: HTTPS + Signature Verification {
      class: https+signature
    }
    a -> b: HTTPS {
      class: https
    }
    a.style.opacity: 0
    b.style.opacity: 0
  }
}

# **.style.font-size: 35
# This is a workaround due to a bug with globs: https://github.com/terrastruct/d2/issues/2709
*.style.font-size: 35
*.*.style.font-size: 35
*.*.*.style.font-size: 35
*.*.*.*.style.font-size: 35
*.*.*.*.*.style.font-size: 35

(** -> **)[*].style.font-size: 30

secureblue-build: Secureblue Build {
  secureblue-github-runner: Secureblue GitHub-Hosted Runner {
    icon: ./assets/github.svg
    stepsecurity-runner: StepSecurity Harden-Runner {
      icon: ./assets/stepsecurity.jpeg
      Build Job: {
        Blue-Build CLI: {
          icon: ./assets/bluebuild.png
        }
      }

      Provenance Job: {
        SLSA generator: {
          icon: ./assets/slsa.png
        }
      }
    }

    stepsecurity-runner.Provenance Job.SLSA Generator -> stepsecurity-runner.Build Job: "generate\nattestation" {
      class: https
    }
  }
}

Trivalent Build: {
  secureblue-github-runner: Secureblue GitHub-Hosted Runner {
    icon: ./assets/github.svg
    stepsecurity-runner: StepSecurity Harden-Runner {
      icon: ./assets/stepsecurity.jpeg

      SRPM Build Job

      Signing Job

      Provenance Job: {
        SLSA Generator: {
          icon: ./assets/slsa.png
        }
      }
    }

    stepsecurity-runner.Provenance Job.SLSA generator -> stepsecurity-runner.Signing Job: "generate\nattestation" {
      class: https
    }
    stepsecurity-runner.Provenance Job.SLSA generator -> stepsecurity-runner.SRPM Build Job: "generate\nattestation" {
      class: https
    }
  }

  aws-runner: "Secureblue AWS-Hosted Runner" {
    icon: ./assets/runson.png
    stepsecurity-runner: "StepSecurity Harden-Runner" {
      icon: ./assets/stepsecurity.jpeg

      RPM Build Job
    }
  }
}

Secureblue Copr Runners: {
  icon: ./assets/copr.png

  Build for bubblejail

  Build for hardened_malloc

  Build for run0edit

  Build for branding

  Build for Trivalent source cache

  Build for Trivalent subresource filter
}

Secureblue Copr Runners -> Fedora Copr: "push build" {
  class: https
}

Secureblue Copr Runners -> Secureblue Github Repos: "pull source" {
  class: https
}

ghcr: "GitHub\nContainer\nRegistry" {
  icon: ./assets/githubcontainerregistry.png
  width: 200
  height: 200
}

User Machine: {
  shape: image
  icon: ./assets/securebluelaptop.png
}

Secureblue RPM Repo: {
  shape: image
  icon: ./assets/secureblue.svg
}

Fedora Copr: {
  shape: image
  icon: ./assets/copr.png
}

Negativo17

Fedora Repos: {
  shape: image
  icon: ./assets/fedora.png
}

Fedora Quay Registry: {
  shape: image
  icon: ./assets/quay.png
}

Secureblue GitHub Repos: {
  shape: image
  icon: ./assets/github.svg
}

User Machine -> ghcr: "pull update" {
  class: https+signature+provenance
}

secureblue-build.secureblue-github-runner.stepsecurity-runner.Provenance Job.SLSA Generator -> ghcr: "push\nattestation" {
  class: https
}
secureblue-build.secureblue-github-runner.stepsecurity-runner.Build Job.Blue-Build CLI -> ghcr: "push image\n& signature" {
  class: https
}
secureblue-build.secureblue-github-runner.stepsecurity-runner.Build Job.Blue-Build CLI -> Fedora Repos: "install packages" {
  class: https+signature
}
secureblue-build.secureblue-github-runner.stepsecurity-runner.Build Job.Blue-Build CLI -> Negativo17: "install packages" {
  class: https+signature
}
secureblue-build.secureblue-github-runner.stepsecurity-runner.Build Job.Blue-Build CLI -> Fedora Copr: "install packages" {
  class: https+signature
}
secureblue-build.secureblue-github-runner.stepsecurity-runner.Build Job.Blue-Build CLI -> Fedora Quay Registry: "pull base image" {
  class: https+signature
}
Trivalent Build.secureblue-github-runner.stepsecurity-runner.Provenance Job.SLSA Generator -> Trivalent Build.aws-runner.stepsecurity-runner.RPM Build Job: "generate\nattestation" {
  class: https
}
Trivalent Build.aws-runner.stepsecurity-runner.RPM Build Job -> Trivalent Build.secureblue-github-runner.stepsecurity-runner.SRPM Build Job: "pull srpm" {
  class: https
}
Trivalent Build.secureblue-github-runner.stepsecurity-runner.Signing Job -> Trivalent Build.aws-runner.stepsecurity-runner.RPM Build Job: "pull rpm" {
  class: https
}
Trivalent Build.secureblue-github-runner.stepsecurity-runner.Signing Job -> Secureblue RPM Repo: "push signed rpm" {
  class: https
}
secureblue-build.secureblue-github-runner.stepsecurity-runner.Build Job.Blue-Build CLI -> Secureblue RPM Repo: "install\ntrivalent rpm" {
  class: https+signature+provenance
}
secureblue-build.secureblue-github-runner.stepsecurity-runner.Build Job.Blue-Build CLI -> Secureblue Github Repos: "pull trivalent\nattestation" {
  class: https
}
Trivalent Build.secureblue-github-runner.stepsecurity-runner.SRPM Build Job -> Fedora Copr: "pull source cache" {
  class: https+signature
}
Trivalent Build.secureblue-github-runner.stepsecurity-runner.Provenance Job.SLSA Generator -> Secureblue GitHub Repos: "push attestation" {
  class: https
}
secureblue-build.secureblue-github-runner -> ghcr: "install\nBlueBuild CLI" {
  class: https+signature+provenance
}
